import Image from 'next/image';

const TorqLogoSmall = () => (
  <div className="flex items-center gap-2">
    <Image
      src="/torq-logo.jpg"
      alt="TORQ Console"
      width={40}
      height={40}
      className="rounded-full"
    />
  </div>
);

const footerLinks = [
  { label: 'Privacy Policy', href: '#' },
  { label: 'Terms of Service', href: '#' },
  { label: 'Contact', href: 'mailto:Admin@TorqBusinessSolutions.com' },
];

export default function Footer() {
  return (
    <footer className="border-t border-torq-border bg-torq-darker">
      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="grid md:grid-cols-3 gap-10 items-center">
          {/* Logo + tagline */}
          <div className="flex flex-col gap-3">
            <TorqLogoSmall />
            <p className="text-xs text-torq-grey leading-relaxed max-w-xs">
              AI business intelligence for serious decision-makers.
              Strategic briefs. Market signals. Document analysis.
            </p>
          </div>

          {/* Navigation */}
          <nav className="flex flex-wrap justify-start md:justify-center gap-6">
            {footerLinks.map((link) => (
              <a
                key={link.label}
                href={link.href}
                className="text-sm text-torq-grey hover:text-torq-grey-light transition-colors"
              >
                {link.label}
              </a>
            ))}
          </nav>

          {/* Copyright + tagline right */}
          <div className="flex flex-col items-start md:items-end gap-2">
            <p className="text-xs text-torq-grey">
              &copy; {new Date().getFullYear()} TORQ Console. All rights reserved.
            </p>
            <p className="text-[11px] text-torq-grey/60">
              Built by Barry Flowers
            </p>
            <p className="text-[10px] text-torq-grey/50 font-mono tracking-wider">
              POWERED BY CLAUDE AI &middot; BUILT FOR OPERATORS
            </p>
          </div>
        </div>

        {/* Bottom disclaimer */}
        <div className="mt-10 pt-6 border-t border-torq-border/50">
          <p className="text-[11px] text-torq-grey/40 leading-relaxed max-w-3xl">
            TORQ Console is an AI-powered intelligence platform. Content generated by TORQ is for informational
            purposes only and does not constitute financial, legal, tax, or investment advice. Always consult
            qualified professionals before making financial or legal decisions. Past performance is not indicative
            of future results.
          </p>
        </div>
      </div>
    </footer>
  );
}
